import type { Component } from 'vue'
import { markRaw } from 'vue'
import {
  ElAutocomplete,
  ElCascader,
  ElCheckboxGroup,
  ElCheckbox,
  ElCheckboxButton,
  ElColorPicker,
  ElDatePicker,
  ElInput,
  ElInputNumber,
  ElInputTag,
  ElMention,
  ElRadioGroup,
  ElRadio,
  ElRadioButton,
  ElRate,
  ElSelect,
  ElOptionGroup,
  ElOption,
  ElSelectV2,
  ElSlider,
  ElSwitch,
  ElTimePicker,
  ElTimeSelect,
  ElTransfer,
  ElTreeSelect,
  ElUpload,
  ElButtonGroup,
  ElButton
} from 'element-plus'

export const dynamicFormComponent: Record<string, Component> = markRaw({
  'el-autocomplete': ElAutocomplete,
  'el-cascader': ElCascader,
  'el-checkbox-group': ElCheckboxGroup,
  'el-checkbox': ElCheckbox,
  'el-checkbox-button': ElCheckboxButton,
  'el-color-picker': ElColorPicker,
  'el-date-picker': ElDatePicker,
  'el-input': ElInput,
  'el-input-number': ElInputNumber,
  'el-input-tag': ElInputTag,
  'el-mention': ElMention,
  'el-radio-group': ElRadioGroup,
  'el-radio': ElRadio,
  'el-radio-button': ElRadioButton,
  'el-rate': ElRate,
  'el-select': ElSelect,
  'el-option-group': ElOptionGroup,
  'el-option': ElOption,
  'el-select-v2': ElSelectV2,
  'el-slider': ElSlider,
  'el-switch': ElSwitch,
  'el-time-picker': ElTimePicker,
  'el-time-select': ElTimeSelect,
  'el-transfer': ElTransfer,
  'el-tree-select': ElTreeSelect,
  'el-upload': ElUpload,
  'el-button-group': ElButtonGroup,
  'el-button': ElButton
})
